name: commit-order

on:
  pull_request:

jobs:
  commit-order:
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-commit-order')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: ./scripts/check_commit_order.sh "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}"
