name: e2e

on:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target test --build-arg ZIG_ARCH=x86_64 -t rmc:test .
      - run: docker run --rm rmc:test
